name: 'Test'
description: 'Run CryFS Tests'
runs:
  using: "composite"
  steps:
    - name: Run tests
      shell: bash
      run: |
        set -v
        echo Running on ${{runner.os}}
        cd build
        ./test/gitversion/gitversion-test
        ./test/cpp-utils/cpp-utils-test
        ./test/parallelaccessstore/parallelaccessstore-test
        ./test/blockstore/blockstore-test
        ./test/blobstore/blobstore-test
        ./test/cryfs/cryfs-test
        
        # TODO Also run on macOS once fixed
        if [[ "${{runner.os}}" == "macOS" ]]; then
          echo Skipping some tests because they are not fixed for macOS yet
        else
          ./test/fspp/fspp-test
          ./test/cryfs-cli/cryfs-cli-test
        fi
